# File generation
HeaderText = '# Test cases automatically generated by AllForOne\n' \
              '# Please check them before you use them.\n\n' \

# Box Drawing Chars
LightHorizontalLine = '\u2500'
LightDownAndRight = '\u250C'
LightVerticalLine = '\u2502'
DoubleHorizontalLine = '\u2550'